substitutions:
  device_name: forecast-lab
  project_name: "forecast.lab"
  friendly_name: "Forecast Lab"
  version: "1.2.0"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: ${project_name}
    version: ${version}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret forecast_api_key

ota:
  - platform: esphome
    password: !secret forecast_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Forecast-Lab Fallback Hotspot"
    password: !secret wifi_password

web_server:
  port: 80
  auth:
    username: !secret forecast_web_username
    password: !secret forecast_web_password

captive_portal:

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13

output:
  - platform: ledc
    pin: GPIO7
    id: bl_pwm

light:
  - platform: monochromatic
    output: bl_pwm
    name: "TFT Backlight"
    id: tft_backlight
    restore_mode: ALWAYS_ON

font:
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: large
    size: 58
  - file: "gfonts://Roboto"
    id: medium
    size: 28
  - file: "gfonts://Roboto"
    id: small
    size: 20
  - file: "gfonts://Roboto"
    id: cyr_small
    size: 20
    glyphs:
      - " "
      - ":"
      - "А"
      - "Б"
      - "В"
      - "Г"
      - "Ґ"
      - "Д"
      - "Е"
      - "Є"
      - "Ж"
      - "З"
      - "И"
      - "І"
      - "Ї"
      - "Й"
      - "К"
      - "Л"
      - "М"
      - "Н"
      - "О"
      - "П"
      - "Р"
      - "С"
      - "Т"
      - "У"
      - "Ф"
      - "Х"
      - "Ц"
      - "Ч"
      - "Ш"
      - "Щ"
      - "Ь"
      - "Ю"
      - "Я"
      - "а"
      - "б"
      - "в"
      - "г"
      - "ґ"
      - "д"
      - "е"
      - "є"
      - "ж"
      - "з"
      - "и"
      - "і"
      - "ї"
      - "й"
      - "к"
      - "л"
      - "м"
      - "н"
      - "о"
      - "п"
      - "р"
      - "с"
      - "т"
      - "у"
      - "ф"
      - "х"
      - "ц"
      - "ч"
      - "ш"
      - "щ"
      - "ь"
      - "ю"
      - "я"

sensor:
  - platform: uptime
    name: "Час роботи"
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi сигнал"
    update_interval: 60s

  - platform: internal_temperature
    name: "Температура процесора"
    update_interval: 60s

  - platform: homeassistant
    id: outside_temp
    entity_id: sensor.vulitsia_t_h_a_temperature

  - platform: homeassistant
    id: outside_humidity
    entity_id: sensor.vulitsia_t_h_a_humidity

  - platform: homeassistant
    id: weather_wind_speed
    entity_id: weather.forecast_home
    attribute: wind_speed

binary_sensor:
  - platform: homeassistant
    id: air_alert
    entity_id: binary_sensor.m_kiiv_air

text_sensor:
  - platform: homeassistant
    id: weather_state
    entity_id: weather.forecast_home

  - platform: wifi_info
    ip_address:
      name: "IP адреса"
    ssid:
      name: "Підключено до"

  - platform: version
    name: "Версія ESPHome"
    hide_timestamp: true

button:
  - platform: restart
    name: "Перезавантаження"
    icon: "mdi:restart"

image:
  - file: mdi:weather-sunny
    id: icon_weather_sunny
    resize: 80x80
    type: binary
  - file: mdi:clouds
    id: icon_weather_cloudy
    resize: 80x80
    type: binary
  - file: mdi:weather-rainy
    id: icon_weather_rainy
    resize: 80x80
    type: binary
  - file: mdi:weather-snowy
    id: icon_weather_snowy
    resize: 80x80
    type: binary
  - file: mdi:weather-lightning
    id: icon_weather_lightning
    resize: 80x80
    type: binary
  - file: mdi:water-percent
    id: icon_weather_humidity
    resize: 26x26
    type: binary
  - file: mdi:weather-windy
    id: icon_weather_windy
    resize: 26x26
    type: binary
  - file: mdi:rocket-launch-outline
    id: icon_rocket_launch
    resize: 20x20
    type: binary

display:
  - platform: mipi_spi
    model: ST7789V
    dimensions:
      width: 240
      height: 320
      offset_width: 0
      offset_height: 0
    rotation: 0
    cs_pin: GPIO12
    dc_pin: GPIO11
    reset_pin: GPIO10
    color_order: rgb
    spi_mode: MODE3
    data_rate: 10MHz
    color_depth: 16
    buffer_size: 20%
    invert_colors: true
    update_interval: 1s
    lambda: |-

      Color bg = id(air_alert).state ? Color(0, 0, 37) : Color::BLACK;
      it.fill(bg);

      if (id(air_alert).state) {
        it.image(10, 12, id(icon_rocket_launch), Color(255, 80, 80), bg);
        it.printf(35, 12, id(cyr_small), Color(255, 80, 80), "ТРИВОГА");
      } else { 
        it.image(10, 12, id(icon_rocket_launch), Color(180, 180, 180), bg);
        it.printf(35, 12, id(cyr_small), Color(180, 180, 180), "Безпечно");
      }

      it.line(10, 40, 230, 40, Color(80, 80, 80));

      it.image(10, 153, id(icon_weather_humidity), Color(215, 185, 155), bg);

      if (!isnan(id(outside_temp).state)) {
        it.printf(100, 70, id(large), Color(200, 200, 200), "%.1f°", id(outside_temp).state);
      } else {
        it.printf(100, 100, id(medium), Color(180, 180, 180), "no data");
      }

      if (!isnan(id(outside_humidity).state)) {
        it.printf(40, 150, id(medium), Color(180, 180, 180), "%.0f%%", id(outside_humidity).state);
      } else {
        it.printf(40, 150, id(medium), Color(180, 180, 180), "no data");
      }

      if (!isnan(id(weather_wind_speed).state)) {
        it.image(100, 153, id(icon_weather_windy), Color(215, 185, 155), bg);
        it.printf(130, 150, id(medium), Color(180, 180, 180), "%.1f m/s", id(weather_wind_speed).state);
      }


      if (id(weather_state).has_state()) {
        auto s = id(weather_state).state;

        if (s == "sunny" || s == "clear-night") {
          it.image(10, 58, id(icon_weather_sunny), Color(0, 215, 255), bg);
        } else if (s == "cloudy" || s == "partlycloudy" || s == "overcast") {
          it.image(10, 58, id(icon_weather_cloudy), Color(240, 185, 115), bg);
        } else if (s == "rainy" || s == "pouring" || s == "lightning-rainy") {
          it.image(10, 58, id(icon_weather_rainy), Color(255, 170, 90), bg);
        } else if (s == "snowy" || s == "snowy-rainy") {
          it.image(10, 58, id(icon_weather_snowy), Color::WHITE, bg);
        } else if (s == "lightning") {
          it.image(10, 58, id(icon_weather_lightning), Color(255, 220, 80), bg);
        }
      } else {
        it.printf(10, 58, id(medium), Color(180, 180, 180), "no data");
      }
